name: Deployment Pipeline


on: 
    push:
        branches: 
            - main

jobs:
    get_repo:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with: 
                fetch-depth: 0
            - uses: actions/setup-node@v3
              with:
                node-version: 14
            - name: Instalar dependencias
              run: npm install
            - name: Lint
              run: npm run eslint
              
            
                